package com.kyi.openfoodfactsapi.utils

import com.kyi.openfoodfactsapi.sources.OffTagged
import com.kyi.openfoodfactsapi.prices.Currency

enum class OpenFoodFactsCountry(override val offTag: String, val iso3Code: String, val currency: Currency?, val wikiUrl: String? = null) : OffTagged {
    ANDORRA("ad", "AND", Currency.EUR),
    UNITED_ARAB_EMIRATES("ae", "ARE", Currency.AED),
    AFGHANISTAN("af", "AFG", Currency.AFN),
    ANTIGUA_AND_BARBUDA("ag", "ATG", Currency.XCD),
    ANGUILLA("ai", "AIA", Currency.XCD),
    ALBANIA("al", "ALB", Currency.ALL),
    ARMENIA("am", "ARM", Currency.AMD),
    ANGOLA("ao", "AGO", Currency.AOA),
    ANTARCTICA("aq", "ATA", null),
    ARGENTINA("ar", "ARG", Currency.ARS, "https://wiki.openfoodfacts.org/Country_Support_-_Argentina"),
    AMERICAN_SAMOA("as", "ASM", Currency.USD, "https://wiki.openfoodfacts.org/Country_Support_-_United_States"),
    AUSTRIA("at", "AUT", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/GermanTeam/Country_Support"),
    AUSTRALIA("au", "AUS", Currency.AUD, "https://wiki.openfoodfacts.org/Country_Support_-_Australia"),
    ARUBA("aw", "ABW", Currency.AWG),
    ALAND_ISLANDS("ax", "ALA", Currency.EUR),
    AZERBAIJAN("az", "AZE", Currency.AZN),
    BOSNIA_AND_HERZEGOVINA("ba", "BIH", Currency.BAM),
    BARBADOS("bb", "BRB", Currency.BBD),
    BANGLADESH("bd", "BGD", Currency.BDT),
    BELGIUM("be", "BEL", Currency.EUR, "https://wiki.openfoodfacts.org/Country_Support_-_Belgium"),
    BURKINA_FASO("bf", "BFA", Currency.XOF),
    BULGARIA("bg", "BGR", Currency.BGN, "https://wiki.openfoodfacts.org/Local_Communities/BulgarianTeam"),
    BAHRAIN("bh", "BHR", Currency.BHD),
    BURUNDI("bi", "BDI", Currency.BIF),
    BENIN("bj", "BEN", Currency.XOF),
    SAINT_BARTHELEMY("bl", "BLM", Currency.EUR),
    BERMUDA("bm", "BMU", Currency.BMD),
    BRUNEI_DARUSSALAM("bn", "BRN", Currency.BND),
    BOLIVIA("bo", "BOL", Currency.BOB),
    BONAIRE("bq", "BES", Currency.USD),
    BRAZIL("br", "BRA", Currency.BRL),
    BAHAMAS("bs", "BHS", Currency.BSD),
    BHUTAN("bt", "BTN", Currency.BTN),
    BOUVET_ISLAND("bv", "BVT", Currency.NOK),
    BOTSWANA("bw", "BWA", Currency.BWP),
    BELARUS("by", "BLR", Currency.BYN),
    BELIZE("bz", "BLZ", Currency.BZD),
    CANADA("ca", "CAN", Currency.CAD, "https://wiki.openfoodfacts.org/Country_Support_-_Canada"),
    COCOS_ISLANDS("cc", "CCK", Currency.AUD),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("cd", "COD", Currency.CDF),
    CENTRAL_AFRICAN_REPUBLIC("cf", "CAF", Currency.XAF),
    CONGO("cg", "COG", Currency.XAF),
    SWITZERLAND("ch", "CHE", Currency.CHF, "https://wiki.openfoodfacts.org/Local_Communities/SwissTeam/Country_Support"),
    COTE_D_IVOIRE("ci", "CIV", Currency.XOF),
    COOK_ISLANDS("ck", "COK", Currency.NZD),
    CHILE("cl", "CHL", Currency.CLP, "https://wiki.openfoodfacts.org/Local_Communities/ChileanTeam"),
    CAMEROON("cm", "CMR", Currency.XAF),
    CHINA("cn", "CHN", Currency.CNY, "https://wiki.openfoodfacts.org/Country_Support_-_China"),
    COLOMBIA("co", "COL", Currency.COP),
    COSTA_RICA("cr", "CRI", Currency.CRC),
    CUBA("cu", "CUB", Currency.CUP),
    CABO_VERDE("cv", "CPV", Currency.CVE),
    CURACAO("cw", "CUW", Currency.ANG),
    CHRISTMAS_ISLAND("cx", "CXR", Currency.AUD),
    CYPRUS("cy", "CYP", Currency.EUR),
    CZECHIA("cz", "CZE", Currency.CZK),
    GERMANY("de", "DEU", Currency.EUR, "https://wiki.openfoodfacts.org/Country_Support_-_Germany"),
    DJIBOUTI("dj", "DJI", Currency.DJF),
    DENMARK("dk", "DNK", Currency.DKK),
    DOMINICA("dm", "DMA", Currency.XCD),
    DOMINICAN_REPUBLIC("do", "DOM", Currency.DOP),
    ALGERIA("dz", "DZA", Currency.DZD),
    ECUADOR("ec", "ECU", Currency.USD),
    ESTONIA("ee", "EST", Currency.EUR),
    EGYPT("eg", "EGY", Currency.EGP),
    WESTERN_SAHARA("eh", "ESH", Currency.MAD),
    ERITREA("er", "ERI", Currency.ERN),
    SPAIN("es", "ESP", Currency.EUR, "https://wiki.openfoodfacts.org/Country_Support_-_Spain"),
    ETHIOPIA("et", "ETH", Currency.ETB),
    FINLAND("fi", "FIN", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FinnishTeam/Country_Support"),
    FIJI("fj", "FJI", Currency.FJD),
    FALKLAND_ISLANDS("fk", "FLK", Currency.FKP),
    MICRONESIA("fm", "FSM", Currency.USD),
    FAROE_ISLANDS("fo", "FRO", Currency.DKK),
    FRANCE("fr", "FRA", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    GABON("ga", "GAB", Currency.XAF),
    UNITED_KINGDOM("uk", "GBR", Currency.GBP, "https://wiki.openfoodfacts.org/Local_Communities/UKTeam"),
    GRENADA("gd", "GRD", Currency.XCD),
    GEORGIA("ge", "GEO", Currency.GEL),
    FRENCH_GUIANA("gf", "GUF", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    GUERNSEY("gg", "GGY", Currency.GBP),
    GHANA("gh", "GHA", Currency.GHS),
    GIBRALTAR("gi", "GIB", Currency.GIP),
    GREENLAND("gl", "GRL", Currency.DKK),
    GAMBIA("gm", "GMB", Currency.GMD),
    GUINEA("gn", "GIN", Currency.GNF),
    GUADELOUPE("gp", "GLP", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    EQUATORIAL_GUINEA("gq", "GNQ", Currency.XAF),
    GREECE("gr", "GRC", Currency.EUR, "https://wiki.openfoodfacts.org/Country_Support_-_Greece"),
    SOUTH_GEORGIA("gs", "SGS", Currency.FKP),
    GUATEMALA("gt", "GTM", Currency.GTQ),
    GUAM("gu", "GUM", Currency.USD),
    GUINEA_BISSAU("gw", "GNB", Currency.XOF),
    GUYANA("gy", "GUY", Currency.GYD),
    HONG_KONG("hk", "HKG", Currency.HKD),
    HEARD_ISLAND("hm", "HMD", Currency.AUD),
    HONDURAS("hn", "HND", Currency.HNL),
    CROATIA("hr", "HRV", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/CroatianTeam"),
    HAITI("ht", "HTI", Currency.HTG),
    HUNGARY("hu", "HUN", Currency.HUF),
    INDONESIA("id", "IDN", Currency.IDR),
    IRELAND("ie", "IRL", Currency.EUR),
    ISRAEL("il", "ISR", Currency.ILS, "https://wiki.openfoodfacts.org/Local_Communities/IsraeliTeam/Country_Support"),
    ISLE_OF_MAN("im", "IMN", Currency.GBP),
    INDIA("in", "IND", Currency.INR, "https://wiki.openfoodfacts.org/Country_Support_-_India"),
    BRITISH_INDIAN_OCEAN_TERRITORY("io", "IOT", Currency.USD),
    IRAQ("iq", "IRQ", Currency.IQD),
    IRAN("ir", "IRN", Currency.IRR),
    ICELAND("is", "ISL", Currency.ISK),
    ITALY("it", "ITA", Currency.EUR, "https://wiki.openfoodfacts.org/Country_Support_-_Italy"),
    JERSEY("je", "JEY", Currency.GBP),
    JAMAICA("jm", "JAM", Currency.JMD),
    JORDAN("jo", "JOR", Currency.JOD),
    JAPAN("jp", "JPN", Currency.JPY, "https://wiki.openfoodfacts.org/Country_Support_-_Japan"),
    KENYA("ke", "KEN", Currency.KES),
    KYRGYZSTAN("kg", "KGZ", Currency.KGS),
    CAMBODIA("kh", "KHM", Currency.KHR),
    KIRIBATI("ki", "KIR", Currency.AUD),
    COMOROS("km", "COM", Currency.KMF),
    SAINT_KITTS_AND_NEVIS("kn", "KNA", Currency.XCD),
    NORTH_KOREA("kp", "PRK", Currency.KPW),
    SOUTH_KOREA("kr", "KOR", Currency.KRW, "https://wiki.openfoodfacts.org/Country_Support_-_South_Korea"),
    KUWAIT("kw", "KWT", Currency.KWD),
    CAYMAN_ISLANDS("ky", "CYM", Currency.KYD),
    KAZAKHSTAN("kz", "KAZ", Currency.KZT),
    LAOS("la", "LAO", Currency.LAK),
    LEBANON("lb", "LBN", Currency.LBP),
    SAINT_LUCIA("lc", "LCA", Currency.XCD),
    LIECHTENSTEIN("li", "LIE", Currency.CHF),
    SRI_LANKA("lk", "LKA", Currency.LKR),
    LIBERIA("lr", "LBR", Currency.LRD),
    LESOTHO("ls", "LSO", Currency.LSL),
    LITHUANIA("lt", "LTU", Currency.EUR),
    LUXEMBOURG("lu", "LUX", Currency.EUR),
    LATVIA("lv", "LVA", Currency.EUR),
    LIBYA("ly", "LBY", Currency.LYD),
    MOROCCO("ma", "MAR", Currency.MAD),
    MONACO("mc", "MCO", Currency.EUR),
    MOLDOVA("md", "MDA", Currency.MDL),
    MONTENEGRO("me", "MNE", Currency.EUR),
    SAINT_MARTIN("mf", "MAF", Currency.EUR),
    MADAGASCAR("mg", "MDG", Currency.MGA),
    MARSHALL_ISLANDS("mh", "MHL", Currency.USD),
    NORTH_MACEDONIA("mk", "MKD", Currency.MKD),
    MALI("ml", "MLI", Currency.XOF),
    MYANMAR("mm", "MMR", Currency.MMK),
    MONGOLIA("mn", "MNG", Currency.MNT),
    MACAO("mo", "MAC", Currency.MOP),
    NORTHERN_MARIANA_ISLANDS("mp", "MNP", Currency.USD),
    MARTINIQUE("mq", "MTQ", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    MAURITANIA("mr", "MRT", Currency.MRU),
    MONTSERRAT("ms", "MSR", Currency.XCD),
    MALTA("mt", "MLT", Currency.EUR),
    MAURITIUS("mu", "MUS", Currency.MUR),
    MALDIVES("mv", "MDV", Currency.MVR),
    MALAWI("mw", "MWI", Currency.MWK),
    MEXICO("mx", "MEX", Currency.MXN, "https://wiki.openfoodfacts.org/Country_Support_-_Mexico"),
    MALAYSIA("my", "MYS", Currency.MYR),
    MOZAMBIQUE("mz", "MOZ", Currency.MZN),
    NAMIBIA("na", "NAM", Currency.NAD),
    NEW_CALEDONIA("nc", "NCL", Currency.XPF, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    NIGER("ne", "NER", Currency.XOF),
    NORFOLK_ISLAND("nf", "NFK", Currency.AUD),
    NIGERIA("ng", "NGA", Currency.NGN, "https://wiki.openfoodfacts.org/Country_Support_-_Nigeria"),
    NICARAGUA("ni", "NIC", Currency.NIO),
    NETHERLANDS("nl", "NLD", Currency.EUR, "https://wiki.openfoodfacts.org/Country_Support_-_Netherlands"),
    NORWAY("no", "NOR", Currency.NOK),
    NEPAL("np", "NPL", Currency.NPR),
    NAURU("nr", "NRU", Currency.AUD),
    NIUE("nu", "NIU", Currency.NZD),
    NEW_ZEALAND("nz", "NZL", Currency.NZD),
    OMAN("om", "OMN", Currency.OMR),
    PANAMA("pa", "PAN", Currency.PAB),
    PERU("pe", "PER", Currency.PEN),
    FRENCH_POLYNESIA("pf", "PYF", Currency.XPF, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    PAPUA_NEW_GUINEA("pg", "PNG", Currency.PGK),
    PHILIPPINES("ph", "PHL", Currency.PHP),
    PAKISTAN("pk", "PAK", Currency.PKR),
    POLAND("pl", "POL", Currency.PLN, "https://wiki.openfoodfacts.org/Country_Support_-_Poland"),
    SAINT_PIERRE_AND_MIQUELON("pm", "SPM", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    PITCAIRN("pn", "PCN", Currency.NZD),
    PUERTO_RICO("pr", "PRI", Currency.USD),
    PALESTINE("ps", "PSE", Currency.ILS),
    PORTUGAL("pt", "PRT", Currency.EUR, "https://wiki.openfoodfacts.org/Country_Support_-_Portugal"),
    PALAU("pw", "PLW", Currency.USD),
    PARAGUAY("py", "PRY", Currency.PYG),
    QATAR("qa", "QAT", Currency.QAR),
    REUNION("re", "REU", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    ROMANIA("ro", "ROU", Currency.RON),
    SERBIA("rs", "SRB", Currency.RSD),
    RUSSIA("ru", "RUS", Currency.RUB, "https://wiki.openfoodfacts.org/Country_Support_-_Russia"),
    RWANDA("rw", "RWA", Currency.RWF),
    SAUDI_ARABIA("sa", "SAU", Currency.SAR),
    SOLOMON_ISLANDS("sb", "SLB", Currency.SBD),
    SEYCHELLES("sc", "SYC", Currency.SCR),
    SUDAN("sd", "SDN", Currency.SDG),
    SWEDEN("se", "SWE", Currency.SEK, "https://wiki.openfoodfacts.org/Local_Communities/SwedishTeam/Country_Support"),
    SINGAPORE("sg", "SGP", Currency.SGD),
    SAINT_HELENA("sh", "SHN", Currency.SHP),
    SLOVENIA("si", "SVN", Currency.EUR),
    SVALBARD_AND_JAN_MAYEN("sj", "SJM", Currency.NOK),
    SLOVAKIA("sk", "SVK", Currency.EUR),
    SIERRA_LEONE("sl", "SLE", Currency.SLE),
    SAN_MARINO("sm", "SMR", Currency.EUR),
    SENEGAL("sn", "SEN", Currency.XOF),
    SOMALIA("so", "SOM", Currency.SOS),
    SURINAME("sr", "SUR", Currency.SRD),
    SOUTH_SUDAN("ss", "SSD", Currency.SSP),
    SAO_TOME_AND_PRINCIPE("st", "STP", Currency.STN),
    EL_SALVADOR("sv", "SLV", Currency.SVC),
    SINT_MAARTEN("sx", "SXM", Currency.ANG),
    SYRIA("sy", "SYR", Currency.SYP),
    ESWATINI("sz", "SWZ", Currency.SZL),
    TURKS_AND_CAICOS_ISLANDS("tc", "TCA", Currency.USD),
    CHAD("td", "TCD", Currency.XAF),
    FRENCH_SOUTHERN_TERRITORIES("tf", "ATF", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    TOGO("tg", "TGO", Currency.XOF),
    THAILAND("th", "THA", Currency.THB, "https://wiki.openfoodfacts.org/Country_Support_-_Thailand"),
    TAJIKISTAN("tj", "TJK", Currency.TJS),
    TOKELAU("tk", "TKL", Currency.NZD),
    TIMOR_LESTE("tl", "TLS", Currency.USD),
    TURKMENISTAN("tm", "TKM", Currency.TMT),
    TUNISIA("tn", "TUN", Currency.TND),
    TONGA("to", "TON", Currency.TOP),
    TURKEY("tr", "TUR", Currency.TRY),
    TRINIDAD_AND_TOBAGO("tt", "TTO", Currency.TTD),
    TUVALU("tv", "TUV", Currency.AUD),
    TAIWAN("tw", "TWN", Currency.TWD, "https://wiki.openfoodfacts.org/Country_Support_-_Taiwan"),
    TANZANIA("tz", "TZA", Currency.TZS),
    UKRAINE("ua", "UKR", Currency.UAH, "https://wiki.openfoodfacts.org/Country_Support_-_Ukraine"),
    UGANDA("ug", "UGA", Currency.UGX),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("um", "UMI", Currency.USD, "https://wiki.openfoodfacts.org/Country_Support_-_United_States"),
    USA("us", "USA", Currency.USD, "https://wiki.openfoodfacts.org/Country_Support_-_United_States"),
    URUGUAY("uy", "URY", Currency.UYU),
    UZBEKISTAN("uz", "UZB", Currency.UZS),
    HOLY_SEE("va", "VAT", Currency.EUR),
    SAINT_VINCENT_AND_THE_GRENADINES("vc", "VCT", Currency.XCD),
    VENEZUELA("ve", "VEN", Currency.VED),
    BRITISH_VIRGIN_ISLANDS("vg", "VGB", Currency.USD),
    US_VIRGIN_ISLANDS("vi", "VIR", Currency.USD),
    VIET_NAM("vn", "VNM", Currency.VND),
    VANUATU("vu", "VUT", Currency.VUV),
    WALLIS_AND_FUTUNA("wf", "WLF", Currency.XPF),
    SAMOA("ws", "WSM", Currency.WST),
    YEMEN("ye", "YEM", Currency.YER),
    MAYOTTE("yt", "MYT", Currency.EUR, "https://wiki.openfoodfacts.org/Local_Communities/FrenchTeam/Country_Support"),
    SOUTH_AFRICA("za", "ZAF", Currency.ZAR),
    ZAMBIA("zm", "ZMB", Currency.ZMW),
    ZIMBABWE("zw", "ZWE", Currency.ZWL);

    companion object {

        fun fromOffTag(offTag: String?): OpenFoodFactsCountry? {
            var lowerOffTag = offTag?.lowercase()
            if (lowerOffTag == "gb") return UNITED_KINGDOM
            return entries.firstOrNull { it.offTag == lowerOffTag }
        }
    }
}