package com.kyi.openfoodfactsapi.prices

enum class Currency(
    val historicalCode: Boolean = false,
    val unofficialCode: Boolean = false,
    val fundsCode: Boolean = false,
    val complementaryCurrency: Boolean = false,
    val noCountry: Boolean = false
) {
    ADP(historicalCode = true),
    AED,
    AFA(historicalCode = true),
    AFN,
    ALK(historicalCode = true),
    ALL,
    AMD,
    ANG,
    AOA,
    AOK(historicalCode = true),
    AON(historicalCode = true),
    AOR(historicalCode = true),
    ARA(historicalCode = true),
    ARL(unofficialCode = true),
    ARM(noCountry = true),
    ARP(historicalCode = true),
    ARS,
    ATS(historicalCode = true),
    AUD,
    AWG,
    AZM(historicalCode = true),
    AZN,
    BAD(historicalCode = true),
    BAM,
    BAN(noCountry = true),
    BBD,
    BDT,
    BEC(historicalCode = true, fundsCode = true),
    BEF(historicalCode = true),
    BEL(historicalCode = true, fundsCode = true),
    BGL(historicalCode = true),
    BGM(noCountry = true),
    BGN,
    BGO(noCountry = true),
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BOL(noCountry = true),
    BOP(historicalCode = true),
    BOV(fundsCode = true),
    BRB(historicalCode = true),
    BRC(historicalCode = true),
    BRE(historicalCode = true),
    BRL,
    BRN(historicalCode = true),
    BRR(historicalCode = true),
    BRZ(noCountry = true),
    BSD,
    BTN,
    BUK(historicalCode = true),
    BWP,
    BYB(historicalCode = true),
    BYN,
    BYR(historicalCode = true),
    BZD,
    CAD,
    CDF,
    CHE(complementaryCurrency = true),
    CHF,
    CHW(complementaryCurrency = true),
    CLE(noCountry = true),
    CLF(fundsCode = true),
    CLP,
    CNH(noCountry = true),
    CNX(noCountry = true),
    CNY,
    COP,
    COU(fundsCode = true),
    CRC,
    CSD(historicalCode = true),
    CSK(historicalCode = true),
    CUC(historicalCode = true),
    CUP,
    CVE,
    CYP(historicalCode = true),
    CZK,
    DDM(historicalCode = true),
    DEM(historicalCode = true),
    DJF,
    DKK,
    DOP,
    DZD,
    ECS(historicalCode = true),
    ECV(historicalCode = true, fundsCode = true),
    EEK(historicalCode = true),
    EGP,
    ERN,
    ESA(historicalCode = true),
    ESB(historicalCode = true),
    ESP(historicalCode = true),
    ETB,
    EUR,
    FIM(historicalCode = true),
    FJD,
    FKP,
    FRF(historicalCode = true),
    GBP,
    GEK(historicalCode = true),
    GEL,
    GHC(historicalCode = true),
    GHS,
    GIP,
    GMD,
    GNF,
    GNS(historicalCode = true),
    GQE(historicalCode = true),
    GRD(historicalCode = true),
    GTQ,
    GWE(historicalCode = true),
    GWP(historicalCode = true),
    GYD,
    HKD,
    HNL,
    HRD(historicalCode = true),
    HRK(historicalCode = true),
    HTG,
    HUF,
    IDR,
    IEP(historicalCode = true),
    ILP(historicalCode = true),
    ILR(historicalCode = true),
    ILS,
    INR,
    IQD,
    IRR,
    ISJ(historicalCode = true),
    ISK,
    ITL(historicalCode = true),
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRH(noCountry = true),
    KRO(noCountry = true),
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LTL(historicalCode = true),
    LTT(historicalCode = true),
    LUC(historicalCode = true, fundsCode = true),
    LUF(historicalCode = true),
    LUL(historicalCode = true, fundsCode = true),
    LVL(historicalCode = true),
    LVR(historicalCode = true),
    LYD,
    MAD,
    MAF(historicalCode = true, unofficialCode = true),
    MCF(historicalCode = true, unofficialCode = true),
    MDC(noCountry = true),
    MDL,
    MGA,
    MGF(historicalCode = true),
    MKD,
    MKN(historicalCode = true, unofficialCode = true),
    MLF(historicalCode = true),
    MMK,
    MNT,
    MOP,
    MRO(historicalCode = true),
    MRU,
    MTL(historicalCode = true),
    MTP(historicalCode = true),
    MUR,
    MVP(noCountry = true),
    MVR,
    MWK,
    MXN,
    MXP(historicalCode = true),
    MXV(fundsCode = true),
    MYR,
    MZE(historicalCode = true),
    MZM(historicalCode = true),
    MZN,
    NAD,
    NGN,
    NIC(historicalCode = true),
    NIO,
    NLG(historicalCode = true),
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEI(historicalCode = true),
    PEN,
    PES(historicalCode = true),
    PGK,
    PHP,
    PKR,
    PLN,
    PLZ(historicalCode = true),
    PTE(historicalCode = true),
    PYG,
    QAR,
    RHD(historicalCode = true),
    ROL(historicalCode = true),
    RON,
    RSD,
    RUB,
    RUR(historicalCode = true),
    RWF,
    SAR,
    SBD,
    SCR,
    SDD(historicalCode = true),
    SDG,
    SDP(historicalCode = true),
    SEK,
    SGD,
    SHP,
    SIT(historicalCode = true),
    SKK(historicalCode = true),
    SLE,
    SLL(historicalCode = true),
    SOS,
    SRD,
    SRG(historicalCode = true),
    SSP,
    STD(historicalCode = true),
    STN,
    SUR(historicalCode = true),
    SVC,
    SYP,
    SZL,
    THB,
    TJR(historicalCode = true),
    TJS,
    TMM(historicalCode = true),
    TMT,
    TND,
    TOP,
    TPE(historicalCode = true),
    TRL(historicalCode = true),
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UAK(historicalCode = true),
    UGS(historicalCode = true),
    UGX,
    USD,
    USN(fundsCode = true),
    USS(historicalCode = true, fundsCode = true),
    UYI(fundsCode = true),
    UYP(historicalCode = true),
    UYU,
    UYW(noCountry = true),
    UZS,
    VEB(historicalCode = true),
    VED,
    VEF(historicalCode = true),
    VES(historicalCode = true),
    VND,
    VNN(noCountry = true),
    VUV,
    WST,
    XAF,
    XAG(noCountry = true),
    XAU(noCountry = true),
    XBA(noCountry = true),
    XBB(noCountry = true),
    XBC(noCountry = true),
    XBD(noCountry = true),
    XCD,
    XDR(noCountry = true),
    XEU(historicalCode = true),
    XFO(historicalCode = true),
    XFU(historicalCode = true),
    XOF,
    XPD(noCountry = true),
    XPF,
    XPT(noCountry = true),
    XRE(historicalCode = true, fundsCode = true),
    XSU(noCountry = true),
    XTS(noCountry = true),
    XUA(noCountry = true),
    XXX(noCountry = true),
    YDD(historicalCode = true),
    YER,
    YUD(historicalCode = true),
    YUM(historicalCode = true),
    YUN(historicalCode = true),
    YUR(historicalCode = true, unofficialCode = true),
    ZAL(historicalCode = true, fundsCode = true),
    ZAR,
    ZMK(historicalCode = true),
    ZMW,
    ZRN(historicalCode = true),
    ZRZ(historicalCode = true),
    ZWD(historicalCode = true),
    ZWL,
    ZWR(historicalCode = true);

    companion object {

        fun fromName(name: String?): Currency? = entries.firstOrNull { it.name == name }
    }
}